/**
 * Card Data for "Guerra all’Ultimo Voto"
 * Total: 90 Cards
 * 1-30: Defense
 * 31-60: Attack
 * 61-90: Strategy/Special
 */

export const CARDS = [
  // --- DEFENSE CARDS (1-30) ---
  { id: 1, name: "Sbianchetto", type: "defense", value: 50, description: "+50 Difesa", effect: { def: 50 }, tags: ["Studio"], targetType: "ally" },
  { id: 2, name: "Ritiro Spirituale", type: "defense", value: 150, description: "+150 Difesa", effect: { def: 150 }, tags: ["Studio"], targetType: "ally" },
  { id: 3, name: "Diario Blindato", type: "defense", value: 80, description: "+80 Difesa", effect: { def: 80 }, tags: ["Studio"], targetType: "ally" },
  { id: 4, name: "Scudo del Secchione", type: "defense", value: 120, description: "+120 Difesa", effect: { def: 120 }, tags: ["Studio"], targetType: "ally" },
  { id: 5, name: "Ripasso Notturno", type: "defense", value: 100, description: "+100 Difesa", effect: { def: 100 }, tags: ["Studio"], targetType: "ally" },
  { id: 6, name: "Manuale Rinforzato", type: "defense", value: 70, description: "+70 Difesa", effect: { def: 70 }, tags: ["Studio"], targetType: "ally" },
  { id: 7, name: "Appunti Fotocopiati", type: "defense", value: 60, description: "+60 Difesa", effect: { def: 60 }, tags: ["Studio"], targetType: "ally" },
  { id: 8, name: "Studio di Gruppo", type: "defense", value: 90, description: "+90 Difesa", effect: { def: 90 }, tags: ["Studio"], targetType: "ally" },
  { id: 9, name: "Tutor Privato", type: "defense", value: 130, description: "+130 Difesa", effect: { def: 130 }, tags: ["Studio"], targetType: "ally" },
  { id: 10, name: "Evidenziatore Epico", type: "defense", value: 40, description: "+40 Difesa", effect: { def: 40 }, tags: ["Studio"], targetType: "ally" },
  { id: 11, name: "Biblioteca Silenziosa", type: "defense", value: 110, description: "+110 Difesa", effect: { def: 110 }, tags: ["Studio"], targetType: "ally" },
  { id: 12, name: "Cuffie Antirumore", type: "defense", value: 75, description: "+75 Difesa", effect: { def: 75 }, tags: ["Studio"], targetType: "ally" },
  { id: 13, name: "Ripetizione Strategica", type: "defense", value: 95, description: "+95 Difesa", effect: { def: 95 }, tags: ["Studio"], targetType: "ally" },
  { id: 14, name: "Schemi Riassuntivi", type: "defense", value: 85, description: "+85 Difesa", effect: { def: 85 }, tags: ["Studio"], targetType: "ally" },
  { id: 15, name: "Post-it Motivazionale", type: "defense", value: 30, description: "+30 Difesa", effect: { def: 30 }, tags: ["Studio"], targetType: "ally" },
  { id: 16, name: "Energia da Caffè", type: "defense", value: 50, description: "+50 Difesa +20 Attacco", effect: { def: 50, atk: 20 }, tags: ["Studio"], targetType: "ally" },
  { id: 17, name: "Aula Vuota", type: "defense", value: 100, description: "+100 Difesa", effect: { def: 100 }, tags: [], targetType: "ally" },
  { id: 18, name: "Foglio Protocollo", type: "defense", value: 60, description: "+60 Difesa", effect: { def: 60 }, tags: ["Studio"], targetType: "ally" },
  { id: 19, name: "Copertina Rigida", type: "defense", value: 80, description: "+80 Difesa", effect: { def: 80 }, tags: ["Studio"], targetType: "ally" },
  { id: 20, name: "Zaino Corazzato", type: "defense", value: 140, description: "+140 Difesa", effect: { def: 140 }, tags: [], targetType: "ally" },
  { id: 21, name: "Assenza Giustificata", type: "defense", value: 0, description: "Annulla ultimo attacco", effect: { cancelLastAttack: true }, tags: [], targetType: "ally" },
  { id: 22, name: "Compito Rimandato", type: "defense", value: 0, description: "Blocca turno avversario", effect: { stun: 1 }, tags: [], targetType: "enemy" },
  { id: 23, name: "Cambio Aula", type: "defense", value: 0, description: "Evita un effetto negativo", effect: { avoidNegativeEffect: true }, tags: [], targetType: "ally" },
  { id: 24, name: "Malattia Strategica", type: "defense", value: 0, description: "Immunità 1 turno", effect: { immunity: 1 }, tags: [], targetType: "ally" },
  { id: 25, name: "Sostegno del Prof", type: "defense", value: 120, description: "+120 Difesa", effect: { def: 120 }, tags: ["Autorità"], targetType: "ally" },
  { id: 26, name: "Silenzio Assoluto", type: "defense", value: -50, description: "Riduce attacco nemico -50", effect: { enemyAtk: -50 }, tags: [], targetType: "enemy" },
  { id: 27, name: "Formula Segreta", type: "defense", value: 70, description: "+70 Difesa", effect: { def: 70 }, tags: ["Studio"], targetType: "ally" },
  { id: 28, name: "Backup Mentale", type: "defense", value: 50, description: "Recupera 50 punti vita", effect: { life: 50 }, tags: [], targetType: "ally" },
  { id: 29, name: "Campanella Salvifica", type: "defense", value: 0, description: "Termina il turno avversario", effect: { endEnemyTurn: true }, tags: [], targetType: "enemy" },
  { id: 30, name: "Scudo di Media Alta", type: "defense", value: 0, description: "Difesa = media voti x10 (Simulato: +100)", effect: { def: 100 }, tags: ["Studio"], targetType: "ally" },

  // --- ATTACK CARDS (31-60) ---
  { id: 31, name: "Ruba Penna", type: "attack", value: 20, description: "+20 Attacco", effect: { atk: 20 }, tags: [], targetType: "ally" },
  { id: 32, name: "Interrogazione a Sorpresa", type: "attack", value: 100, description: "+100 Attacco", effect: { atk: 100 }, tags: ["Autorità"], targetType: "ally" },
  { id: 33, name: "Compito a Tradimento", type: "attack", value: 120, description: "+120 Attacco", effect: { atk: 120 }, tags: ["Studio"], targetType: "ally" },
  { id: 34, name: "Domanda Bastarda", type: "attack", value: 80, description: "+80 Attacco", effect: { atk: 80 }, tags: ["Studio"], targetType: "ally" },
  { id: 35, name: "Panico da Lavagna", type: "attack", value: 90, description: "+90 Attacco", effect: { atk: 90 }, tags: [], targetType: "ally" },
  { id: 36, name: "Zero Improvviso", type: "attack", value: 200, description: "-200 Vita avversario", effect: { directDamage: 200 }, tags: [], targetType: "enemy" },
  { id: 37, name: "Verifica a Tempo", type: "attack", value: 70, description: "+70 Attacco", effect: { atk: 70 }, tags: ["Studio"], targetType: "ally" },
  { id: 38, name: "Professore Intransigente", type: "attack", value: 150, description: "+150 Attacco", effect: { atk: 150 }, tags: ["Autorità"], targetType: "ally" },
  { id: 39, name: "Consegna Anticipata", type: "attack", value: 60, description: "+60 Attacco", effect: { atk: 60 }, tags: [], targetType: "ally" },
  { id: 40, name: "Tema Impossibile", type: "attack", value: 110, description: "+110 Attacco", effect: { atk: 110 }, tags: ["Studio"], targetType: "ally" },
  { id: 41, name: "Quiz a Crocette Ingannevole", type: "attack", value: 75, description: "+75 Attacco", effect: { atk: 75 }, tags: ["Studio"], targetType: "ally" },
  { id: 42, name: "Bocciatura Parziale", type: "attack", value: -100, description: "-100 Difesa nemico", effect: { enemyDef: -100 }, tags: ["Autorità"], targetType: "enemy" },
  { id: 43, name: "Penna Scarica", type: "attack", value: -80, description: "-80 Attacco nemico", effect: { enemyAtk: -80 }, tags: [], targetType: "enemy" },
  { id: 44, name: "Lavagna Ostile", type: "attack", value: 50, description: "+50 Attacco +50 Difesa", effect: { atk: 50, def: 50 }, tags: [], targetType: "ally" },
  { id: 45, name: "Richiamo Ufficiale", type: "attack", value: 120, description: "-120 Vita", effect: { directDamage: 120 }, tags: ["Autorità"], targetType: "enemy" },
  { id: 46, name: "Media Abbassata", type: "attack", value: 90, description: "-90 Vita", effect: { directDamage: 90 }, tags: [], targetType: "enemy" },
  { id: 47, name: "Esame Finale", type: "attack", value: 200, description: "+200 Attacco", effect: { atk: 200 }, tags: ["Studio"], targetType: "ally" },
  { id: 48, name: "Prova Invalsi", type: "attack", value: 130, description: "+130 Attacco", effect: { atk: 130 }, tags: ["Studio"], targetType: "ally" },
  { id: 49, name: "Colloquio Inaspettato", type: "attack", value: 95, description: "+95 Attacco", effect: { atk: 95 }, tags: ["Autorità"], targetType: "ally" },
  { id: 50, name: "Debito Formativo", type: "attack", value: 150, description: "-150 Vita", effect: { directDamage: 150 }, tags: ["Autorità"], targetType: "enemy" },
  { id: 51, name: "Ritardo Fatale", type: "attack", value: -60, description: "-60 Difesa", effect: { enemyDef: -60 }, tags: [], targetType: "enemy" },
  { id: 52, name: "Foglio Strappato", type: "attack", value: -100, description: "-100 Difesa", effect: { enemyDef: -100 }, tags: [], targetType: "enemy" },
  { id: 53, name: "Distrazione Totale", type: "attack", value: 2, description: "Attacco doppio questo turno", effect: { atkMultiplier: 2 }, tags: [], targetType: "ally" },
  { id: 54, name: "Prof di Matematica", type: "attack", value: 170, description: "+170 Attacco", effect: { atk: 170 }, tags: ["Autorità"], targetType: "ally" },
  { id: 55, name: "Formula Dimenticata", type: "attack", value: 100, description: "-100 Vita", effect: { directDamage: 100 }, tags: ["Studio"], targetType: "enemy" },
  { id: 56, name: "Ansia da Prestazione", type: "attack", value: -70, description: "-70 Difesa", effect: { enemyDef: -70 }, tags: [], targetType: "enemy" },
  { id: 57, name: "Esposizione Pubblica", type: "attack", value: 85, description: "+85 Attacco", effect: { atk: 85 }, tags: [], targetType: "ally" },
  { id: 58, name: "Media del 5.9", type: "attack", value: 120, description: "-120 Vita", effect: { directDamage: 120 }, tags: [], targetType: "enemy" },
  { id: 59, name: "Punto di Penalità", type: "attack", value: 40, description: "-40 Vita", effect: { directDamage: 40 }, tags: ["Autorità"], targetType: "enemy" },
  { id: 60, name: "Trappola Didattica", type: "attack", value: 2, description: "Prossimo attacco raddoppiato", effect: { nextAtkMultiplier: 2 }, tags: [], targetType: "ally" },

  // --- STRATEGY / SPECIAL CARDS (61-90) ---
  { id: 61, name: "Colpo di Genio", type: "special", value: 2, description: "Raddoppia attacco", effect: { atkMultiplier: 2 }, tags: [], targetType: "ally" },
  { id: 62, name: "Copia Controllata", type: "special", value: 0, description: "Copia effetto ultima carta", effect: { copyLastEffect: true }, tags: [], targetType: "ally" },
  { id: 63, name: "Bigino Nascosto", type: "special", value: 150, description: "+150 Attacco ma perdi 50 Difesa", effect: { atk: 150, def: -50 }, tags: ["Studio"], targetType: "ally" },
  { id: 64, name: "Aiuto da Casa", type: "special", value: 100, description: "Recupera 100 Vita", effect: { life: 100 }, tags: [], targetType: "ally" },
  { id: 65, name: "Ricorso al Preside", type: "special", value: 0, description: "Annulla ultima carta", effect: { cancelLastCard: true }, tags: ["Autorità"], targetType: "any" },
  { id: 66, name: "Cambio Banco", type: "special", value: 0, description: "Scambia attacco/difesa", effect: { swapAtkDef: true }, tags: [], targetType: "ally" },
  { id: 67, name: "Studio Estremo", type: "special", value: 200, description: "+200 Difesa ma salti turno", effect: { def: 200, stun: 1 }, tags: ["Studio"], targetType: "ally" },
  { id: 68, name: "Notte in Bianco", type: "special", value: 180, description: "+180 Attacco, -80 Difesa", effect: { atk: 180, def: -80 }, tags: ["Studio"], targetType: "ally" },
  { id: 69, name: "Bonus Crediti", type: "special", value: 100, description: "+100 Vita", effect: { life: 100 }, tags: [], targetType: "ally" },
  { id: 70, name: "Autogestione", type: "special", value: 0, description: "Entrambi saltano turno", effect: { bothStun: 1 }, tags: [], targetType: "enemy" },
  { id: 71, name: "Assemblea Straordinaria", type: "special", value: 0, description: "Resetta effetti attivi", effect: { resetEffects: true }, tags: [], targetType: "any" },
  { id: 72, name: "Colloquio Genitori", type: "special", value: 150, description: "+150 Difesa", effect: { def: 150 }, tags: ["Autorità"], targetType: "ally" },
  { id: 73, name: "Cambio Prof", type: "special", value: 0, description: "Mescola effetti casuali", effect: { randomizeEffects: true }, tags: ["Autorità"], targetType: "any" },
  { id: 74, name: "Recupero Estivo", type: "special", value: 300, description: "Torna a 300 Vita", effect: { setLife: 300 }, tags: [], targetType: "ally" },
  { id: 75, name: "Media Perfetta", type: "special", value: 250, description: "+250 Attacco", effect: { atk: 250 }, tags: [], targetType: "ally" },
  { id: 76, name: "Crisi Esistenziale", type: "special", value: -150, description: "-150 Vita entrambi", effect: { bothDamage: 150 }, tags: [], targetType: "enemy" },
  { id: 77, name: "Tutoraggio Intensivo", type: "special", value: 100, description: "+100 Attacco +100 Difesa", effect: { atk: 100, def: 100 }, tags: ["Studio"], targetType: "ally" },
  { id: 78, name: "Burnout", type: "special", value: 300, description: "Salti 2 turni ma poi +300 Attacco", effect: { stun: 2, delayAtk: 300 }, tags: [], targetType: "ally" },
  { id: 79, name: "Ultimo Banco", type: "special", value: 0, description: "Immunità attacchi diretti", effect: { directDamageImmunity: true }, tags: [], targetType: "ally" },
  { id: 80, name: "Bonus Frequenza", type: "special", value: 80, description: "+80 Vita", effect: { life: 80 }, tags: [], targetType: "ally" },
  { id: 81, name: "Recupero Lampo", type: "special", value: 120, description: "Cura 120 Vita", effect: { life: 120 }, tags: [], targetType: "ally" },
  { id: 82, name: "Copertura di Classe", type: "special", value: 0.5, description: "Riduce danni 50% turno", effect: { damageReduction: 0.5 }, tags: [], targetType: "ally" },
  { id: 83, name: "Colpo Basso", type: "special", value: 0, description: "Ignora difesa", effect: { ignoreDefense: true }, tags: [], targetType: "enemy" },
  { id: 84, name: "Media del 10", type: "special", value: 300, description: "+300 Attacco", effect: { atk: 300 }, tags: [], targetType: "ally" },
  { id: 85, name: "Esame Orale Supremo", type: "special", value: 220, description: "+220 Attacco", effect: { atk: 220 }, tags: ["Studio"], targetType: "ally" },
  { id: 86, name: "Patto di Classe", type: "special", value: 100, description: "Entrambi +100 Difesa", effect: { bothDef: 100 }, tags: [], targetType: "ally" },
  { id: 87, name: "Interrogazione Programmata", type: "special", value: 140, description: "+140 Attacco", effect: { atk: 140 }, tags: ["Autorità"], targetType: "ally" },
  { id: 88, name: "Appello Straordinario", type: "special", value: 0, description: "Ripeti ultima carta", effect: { repeatLastCard: true }, tags: [], targetType: "ally" },
  { id: 89, name: "Rientro Strategico", type: "special", value: 150, description: "+150 Difesa", effect: { def: 150 }, tags: [], targetType: "ally" },
  { id: 90, name: "Guerra all’Ultimo Voto", type: "special", value: 500, description: "+500 Attacco se Vita < 200", effect: { lowLifeAtk: 500 }, tags: [], targetType: "ally" }
];

